#!/bin/bash
fetcher --alwaysUseAuth --file="~/gitf_config.json" --url=$*
# https://github.com/Gyumeijie/github-files-fetcher#authentication
# Using --alwaysUseAuth coz: https://github.com/Gyumeijie/github-files-fetcher#behavior
# *IMPORTANT: CONFIG FILE IS SAVED @ ~/gitf_config.json
