#!/bin/bash
set -x
#git pull --all #Note << that script won't merge any change to the local branch.
hub sync ## Note, << that script will automatically merge if no local commits are made to the branches thats changed on origin, yikes!!! Also, it notifies that local commits to that branch were made and thus didn't merge the branch from the origin, yikes!!
