#!/bin/bash
devilspie2 --folder ~/my_bin/files/devilspie2
# This file is configure to run on system startup(possible user login event though), and now emoji-picker just open with "Always on visible workspace".
