#!/bin/bash
# :: ^^ Note you have to remove #!/bin/bash from this file to be able to run it via gnome-shortcuts, yikes!
# amazing link: https://superuser.com/a/1627429/776589
# also see the "See also" links they are awesome to understand the js api of gnome, yikes!
if /home/array/my_bin/aliases/getWindows | grep "Emoji Picker"
then
  if /home/array/my_bin/isFocusEmojiPicker
  then
  /home/array/my_bin/minimize_emoji_picker
#    nautilus &
  else
    /home/array/my_bin/focus_emoji_picker
#    gedit &
  fi
else
  emoji-picker
fi
#Usage Simply use win+d to open emojipicker and use win+x to minimise it, and now it works across all workspaces without getting intermingled, yo!!
# ::Testing below::
#/home/array/my_bin/aliases/getWindows | grep "Emoji Picker" && /home/array/my_bin/focus_emoji_picker
#gedit
#Nothing works for executing my nodescript using node script.
#gnome-terminal -- /home/array/my_bin/aliases/run_emoji_picker
#node run_emoji_picker
#NOTE: I am using bash's if else loop to execute it coz using node script (with shebang) fails to execute no matter what all I try, and with the current setup it just works!
