#!/bin/bash
#::Testing below:: with sleep function, so you can switch focus to emoji_picker to test behaviour.
#sleep 2 && gdbus call \
gdbus call \
  --session \
  --dest org.gnome.Shell \
  --object-path /org/gnome/Shell \
  --method org.gnome.Shell.Eval "
    global
      .get_window_actors()
      .map(a=>a.meta_window)
      .find(w=>w.has_focus())
      .get_wm_class()" \
  | cut -d'"' -f 2 | grep 'Emoji Picker'
