#!/bin/bash
# Not putting `set -x` intentionally here coz it prints if condition then too.
if  [ $# -eq 0 ]
then
set -x
  code -r .
# Here -r means to use existing window to open the desired file/folder, yikes!!
else
set -x
  code $*
fi

# Check if arguments are passed or not: https://stackoverflow.com/a/6482403
# Using if else in bash: https://linuxize.com/post/bash-if-else-statement/
