#!/bin/node
const {exec} = require("child_process");
// get sudo permissions.
exec("sudo echo Thanks for sudo permissions...", (e, so, se) => {
  console.log(so);
});

// my cli
let input = process.argv[2];

exec(command, (error, stdout, stderr) => {
  if (error) {
    console.log(`error: ${error.message}`);
    return;
  }
  if (stderr) {
    console.log(`stderr: ${stderr}`);
    return;
  }
  console.log(`stdout: ${stdout}`);
});
