#!/usr/bin/fish
ls -a -I . -I .. --color | lolcat
#ls $@ -a --color -I . -I ..
# https://unix.stackexchange.com/a/147243
#
# Ommit . and .. from the ouput using `-I` option:
# src: https://askubuntu.com/a/512963
