#!/bin/node
var exec = require("child_process").exec;

var args = " -X POST -d '{\"title\": \"Test\" }' -H 'Content-Type: application/json' http://localhost:3000/api/hello";

exec("curl " + args, function (error, stdout, stderr) {
  console.log("stdout: " + stdout);
  console.log("stderr: " + stderr);
  if (error !== null) {
    console.log("exec error: " + error);
  }
});
