trailingComma: 'es5'
tabWidth: 2
semi: false
# ^^ This is for semicolon.
singleQuote: true
# ^^ This rule doesn't specify for jsx.
jsxSingleQuote: true
# ^^ This rule specify for jsx only.
bracketSpacing: false
useTabs: true
#
# Php formatting options below -
braceStyle: 1tbs
# ^^ this sets the brace style for php formatting like to put on same line.
# Read more about php formatting @ https://github.com/prettier/plugin-php
